version: '2'
services:
  db:
    image: mariadb:${DB_TAG}
    volumes:
      - "${DB_DIRECTORY}:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  php8:
    depends_on:
      - db
    build:
      context: ./config
      args:
        PHP_TAG: ${PHP_TAG}
      dockerfile: php.dockerfile
    image: php8:${PHP_TAG}
    volumes:
      - ${PHP_DIRECTORY}:/var/www/html
      - ./config/php.www.conf:/usr/local/etc/php-fpm.d/zzz-php.conf
      - ./config/php.override.ini:/usr/local/etc/php/conf.d/override.ini
    restart: always

  web:
    depends_on:
      - php8
    image: nginx:latest
    ports:
      - "127.0.0.1:7000:80"
    volumes:
      - ./config/nginx.internal.conf:/etc/nginx/conf.d/default.conf
      - ${WEB_DIRECTORY}:/var/www/html
    restart: always
